{"name": "test_alogin", "status": "broken", "statusDetails": {"message": "TypeError: finds_and_click() takes 3 positional arguments but 4 were given", "trace": "self = <testcase.test_demo2.TestDemo2 object at 0x00000255508DD308>\nbrowser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e7bdf67cad1ab64c96ae10ce167d772c\")>\n\n    @pytest.mark.run(order=1)\n    @allure.story(\"登录\")\n    @allure.step(\"成功登录\")\n    def test_alogin(self,browser):\n        # self.chrome.start().goto_main().login().creat_company()\n        #self.chrome.goto_main().goto_login().login()\n>       self.chrome.goto_main(browser).goto_login().login()\n\ntest_demo2.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\page\\loginpage.py:28: in login\n    self.parse(\"../data/loginpage.yml\",\"goto_login\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.loginpage.LoginPage object at 0x00000255509C37C8>\nyaml_path = '../data/loginpage.yml', fun_name = 'goto_login'\n\n    def parse(self, yaml_path, fun_name):\n        \"\"\"\n        解析关键字，实现相应动作\n        :param yaml_path:\n        :param fun_name:\n        :return:\n        \"\"\"\n        with open(yaml_path, \"r\", encoding=\"utf-8\") as f:\n            function = yaml.load(f,Loader=yaml.FullLoader)\n            # 从关键字中取出一个函数\n        steps = function.get(fun_name)\n        # 解析每一组关键字\n        for step in steps:\n            # 如果发现关键字是 find_and_click ，就调用已经封装好的 find_and_click 即可\n            if step.get(\"action\") == \"find_and_click\":\n                self.find_and_click(step.get('locator'), step.get('value'))\n            elif step.get(\"action\") == \"find_and_send\":\n                self.find_and_send(step.get('locator'), step.get('value'),  step.get('content'))\n            elif step.get(\"action\") == \"finds_and_click\":\n>               self.finds_and_click(step.get('locator'), step.get('value'), step.get('index'))\nE               TypeError: finds_and_click() takes 3 positional arguments but 4 were given\n\n..\\page\\basepage.py:115: TypeError"}, "steps": [{"name": "成功登录", "status": "broken", "statusDetails": {"message": "TypeError: finds_and_click() takes 3 positional arguments but 4 were given\n", "trace": "  File \"D:\\LearnProject\\SeleniumProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"D:\\LearnProject\\SeleniumProject\\testcase\\test_demo2.py\", line 27, in test_alogin\n    self.chrome.goto_main(browser).goto_login().login()\n  File \"D:\\LearnProject\\SeleniumProject\\page\\loginpage.py\", line 28, in login\n    self.parse(\"../data/loginpage.yml\",\"goto_login\")\n  File \"D:\\LearnProject\\SeleniumProject\\page\\basepage.py\", line 115, in parse\n    self.finds_and_click(step.get('locator'), step.get('value'), step.get('index'))\n"}, "parameters": [{"name": "browser", "value": "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"e7bdf67cad1ab64c96ae10ce167d772c\")>"}], "start": 1618672164253, "stop": 1618672164264}], "start": 1618672164252, "stop": 1618672164266, "uuid": "a9a26a60-31f9-44fa-b61e-cd8468717221", "historyId": "2f8d6cb02e01ad48229682220e61e969", "testCaseId": "242e6a3309fdc0b638d4ff3c9be3c0a7", "fullName": "test_demo2.TestDemo2#test_alogin", "labels": [{"name": "story", "value": "登录"}, {"name": "feature", "value": "网点模块"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_demo2"}, {"name": "subSuite", "value": "TestDemo2"}, {"name": "host", "value": "DESKTOP-17T1KCH"}, {"name": "thread", "value": "24344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo2"}]}